# Generated by Django 6.0.4 on 2026-06-25 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_badania', models.DateTimeField(auto_now_add=True)),
                ('etap', models.CharField(choices=[('0', 'Etap 0 (Początek obserwacji)'), ('1', 'Etap I (6 miesięcy od pierwszego badania)'), ('2', 'Etap II (12 miesięcy od pierwszego badania)')], max_length=10)),
                ('plec', models.CharField(choices=[('kobieta', 'Kobieta'), ('mezczyzna', 'Mężczyzna')], max_length=20)),
                ('wiek', models.PositiveIntegerField()),
                ('masa_ciala', models.FloatField()),
                ('wzrost', models.FloatField()),
                ('operacja_bariatryczna', models.BooleanField(default=False)),
                ('data_operacji_bariatrycznej', models.CharField(blank=True, max_length=50)),
                ('maksymalna_masa_przed_operacja', models.FloatField(blank=True, null=True)),
                ('cpap', models.CharField(blank=True, max_length=100)),
                ('cpap_czas_stosowania', models.CharField(blank=True, max_length=100)),
                ('cpap_godziny_snu', models.CharField(blank=True, max_length=50)),
                ('cpap_zmiana_cisnienia', models.CharField(blank=True, max_length=100)),
                ('choroby', models.TextField(blank=True)),
                ('fizjoterapia', models.CharField(blank=True, max_length=100)),
                ('charakter_aktywnosci', models.CharField(blank=True, max_length=100)),
                ('alkohol_przed_snem', models.CharField(blank=True, max_length=100)),
                ('palenie', models.BooleanField(default=False)),
                ('pozycja_snu', models.CharField(blank=True, max_length=100)),
                ('obwod_szyi', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=20, unique=True)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Epworth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pytanie_1', models.IntegerField()),
                ('pytanie_2', models.IntegerField()),
                ('pytanie_3', models.IntegerField()),
                ('pytanie_4', models.IntegerField()),
                ('pytanie_5', models.IntegerField()),
                ('pytanie_6', models.IntegerField()),
                ('pytanie_7', models.IntegerField()),
                ('pytanie_8', models.IntegerField()),
                ('wynik', models.IntegerField(default=0)),
                ('data_wypelnienia', models.DateTimeField(auto_now_add=True)),
                ('interpretacja', models.CharField(blank=True, max_length=100)),
                ('badanie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='epworth', to='kwestionariusz.badanie')),
            ],
        ),
        migrations.CreateModel(
            name='IPAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szpital', models.BooleanField(default=False)),
                ('choroba', models.BooleanField(default=False)),
                ('rehabilitacja', models.BooleanField(default=False)),
                ('urlop', models.BooleanField(default=False)),
                ('rekonwalescencja', models.BooleanField(default=False)),
                ('ciaza', models.BooleanField(default=False)),
                ('intensywne_dni', models.IntegerField(default=0)),
                ('intensywne_minuty', models.IntegerField(default=0)),
                ('umiarkowane_dni', models.IntegerField(default=0)),
                ('umiarkowane_minuty', models.IntegerField(default=0)),
                ('chodzenie_dni', models.IntegerField(default=0)),
                ('chodzenie_minuty', models.IntegerField(default=0)),
                ('siedzenie_minuty_dziennie', models.IntegerField(default=0)),
                ('wynik_met', models.FloatField(default=0)),
                ('kategoria', models.CharField(blank=True, max_length=50)),
                ('data_wypelnienia', models.DateTimeField(auto_now_add=True)),
                ('badanie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ipaq', to='kwestionariusz.badanie')),
            ],
        ),
        migrations.AddField(
            model_name='badanie',
            name='pacjent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badania', to='kwestionariusz.pacjent'),
        ),
        migrations.CreateModel(
            name='Pittsburgh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godzina_polozenia', models.TimeField(blank=True, null=True)),
                ('czas_zasypiania_minuty', models.IntegerField(default=0)),
                ('godzina_wstawania', models.TimeField(blank=True, null=True)),
                ('godziny_snu', models.FloatField(default=0)),
                ('nie_zasnal_30_min', models.IntegerField(default=0)),
                ('pobudka_w_nocy', models.IntegerField(default=0)),
                ('toaleta', models.IntegerField(default=0)),
                ('problemy_z_oddychaniem', models.IntegerField(default=0)),
                ('kaszel_chrapanie', models.IntegerField(default=0)),
                ('za_zimno', models.IntegerField(default=0)),
                ('za_cieplo', models.IntegerField(default=0)),
                ('zle_sny', models.IntegerField(default=0)),
                ('bol', models.IntegerField(default=0)),
                ('inne_powody', models.IntegerField(default=0)),
                ('inne_powody_opis', models.TextField(blank=True)),
                ('jakosc_snu', models.IntegerField(default=0)),
                ('leki_nasenne', models.IntegerField(default=0)),
                ('problemy_z_czuwaniem', models.IntegerField(default=0)),
                ('brak_energii', models.IntegerField(default=0)),
                ('wynik', models.IntegerField(default=0)),
                ('data_wypelnienia', models.DateTimeField(auto_now_add=True)),
                ('badanie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pittsburgh', to='kwestionariusz.badanie')),
            ],
        ),
    ]
