# Generated by Django 6.0.4 on 2026-06-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwestionariusz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badanie',
            name='etap',
            field=models.CharField(blank=True, choices=[('0', 'Etap 0 (Początek obserwacji)'), ('1', 'Etap I (6 miesięcy od pierwszego badania)'), ('2', 'Etap II (12 miesięcy od pierwszego badania)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='badanie',
            name='masa_ciala',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='badanie',
            name='plec',
            field=models.CharField(blank=True, choices=[('kobieta', 'Kobieta'), ('mezczyzna', 'Mężczyzna')], max_length=20),
        ),
        migrations.AlterField(
            model_name='badanie',
            name='wiek',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='badanie',
            name='wzrost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
